No exceptions occurred
I'm inside finally block
Test completed
